=== activityworkshop/GpsQuest/data/quest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Quest" type="QuestType"/>
  <xs:complexType name="DescriptionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="lang" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StartSceneType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="HeadType">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="xs:string" name="Id"/>
      <xs:element type="DescriptionType" name="Description" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="xs:string" name="Author"/>
      <xs:element type="VariablesType" name="Variables"/>
      <xs:element type="xs:string" name="Timers"/>
      <xs:element type="StartSceneType" name="StartScene"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PointType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="lat" use="required"/>
        <xs:attribute type="xs:string" name="lon" use="required"/>
        <xs:attribute type="xs:string" name="radius" use="required"/>
        <xs:attribute type="xs:string" name="enter"/>
        <xs:attribute type="xs:string" name="exit"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ZonesType">
    <xs:sequence>
      <xs:element type="PointType" name="Point" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="var" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
        <xs:attribute type="xs:string" name="comparison" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GoToSceneType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ActionType">
    <xs:sequence>
      <xs:element type="SetVariableType" name="SetVariable" minOccurs="0"/>
      <xs:element type="GoToSceneType" name="GoToScene"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TriggerType">
    <xs:sequence>
      <xs:element type="ConditionType" name="Condition" minOccurs="0"/>
      <xs:element type="ActionType" name="Action"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
  </xs:complexType>
  <xs:complexType name="SetVariableType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="var" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TriggersType">
    <xs:sequence>
      <xs:element type="TriggerType" name="Trigger" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SceneType" mixed="true">
    <xs:sequence>
      <xs:element name="Text" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="xs:string" name="Finish" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="lang" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ScenesType">
    <xs:sequence>
      <xs:element type="SceneType" name="Scene" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="QuestType">
    <xs:sequence>
      <xs:element type="HeadType" name="Head"/>
      <xs:element type="ZonesType" name="Zones"/>
      <xs:element type="TriggersType" name="Triggers"/>
      <xs:element type="ScenesType" name="Scenes"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== activityworkshop/GpsQuest/data/a_to_b/main.xml
<Quest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../quest.xsd">
    <Head>
        <Name>From A to B</Name>
        <Id/>
        <Description>Simple example quest to go from point A to point B</Description>
        <Author>ActivityWorkshop</Author>
        <Variables>
            <Variable id="visitedA" value="0"/>
        </Variables>
        <Timers/>
        <StartScene id="Intro"/>
    </Head>
    <Zones>
        <Point id="PointA" lat="0.01" lon="0.0" radius="50" enter="enterA1,enterA2" exit="exitA"/>
        <Point id="PointB" lat="0.03" lon="0.2" radius="20" enter="enterB1,enterB2"/>
    </Zones>
    <Triggers>
        <Trigger id="enterA1">
            <Condition var="visitedA" value="1" comparison="eq"/>
            <Action>
                <GoToScene id="RevisitedStart"/>
            </Action>
        </Trigger>
        <Trigger id="enterA2">
            <Condition var="visitedA" value="0" comparison="eq"/>
            <Action>
                <SetVariable var="visitedA" value="1"/>
                <GoToScene id="ReachedA"/>
            </Action>
        </Trigger>
        <Trigger id="exitA">
            <Action>
                <SetVariable var="visitedA" value="1"/>
                <GoToScene id="Started"/>
            </Action>
        </Trigger>
        <Trigger id="enterB1">
            <Condition var="visitedA" value="0" comparison="eq"/>
            <Action>
                <GoToScene id="HaventVisitedStart"/>
            </Action>
        </Trigger>
        <Trigger id="enterB2">
            <Condition var="visitedA" value="1" comparison="eq"/>
            <Action>
                <GoToScene id="Finish"/>
            </Action>
        </Trigger>
    </Triggers>
    <Scenes>
    	<Scene id="Intro"/>
    	<Scene id="ReachedA"/>
    	<Scene id="RevisitedStart"/>
    	<Scene id="Started"/>
    	<Scene id="HaventVisitedStart"/>
    	<Scene id="Finish">
            <Text>Congratulations</Text>
    		<Finish/>
    	</Scene>
    </Scenes>
</Quest>

=== activityworkshop/GpsQuest/data/a_to_b_multilang/main.xml
<Quest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../quest.xsd">
    <Head>
        <Name>From A to B</Name>
        <Id/>
        <Description lang="en">Simple example quest to go from point A to point B (with multiple languages)</Description>
        <Description lang="de">Einfaches Beispiel Quest um von A zum B zu gelangen (mit mehreren Sprachen)</Description>
        <Author>ActivityWorkshop</Author>
        <Variables>
            <Variable id="visitedA" value="0"/>
        </Variables>
        <Timers/>
        <StartScene id="Intro"/>
    </Head>
    <Zones>
        <Point id="PointA" lat="0.01" lon="0.0" radius="50" enter="enterA1,enterA2" exit="exitA"/>
        <Point id="PointB" lat="0.03" lon="0.2" radius="20" enter="enterB1,enterB2"/>
    </Zones>
    <Triggers>
        <Trigger id="enterA1">
            <Condition var="visitedA" value="1" comparison="eq"/>
            <Action>
                <GoToScene id="RevisitedStart"/>
            </Action>
        </Trigger>
        <Trigger id="enterA2">
            <Condition var="visitedA" value="0" comparison="eq"/>
            <Action>
                <SetVariable var="visitedA" value="1"/>
                <GoToScene id="ReachedA"/>
            </Action>
        </Trigger>
        <Trigger id="exitA">
            <Action>
                <SetVariable var="visitedA" value="1"/>
                <GoToScene id="Started"/>
            </Action>
        </Trigger>
        <Trigger id="enterB1">
            <Condition var="visitedA" value="0" comparison="eq"/>
            <Action>
                <GoToScene id="HaventVisitedStart"/>
            </Action>
        </Trigger>
        <Trigger id="enterB2">
            <Condition var="visitedA" value="1" comparison="eq"/>
            <Action>
                <GoToScene id="Finish"/>
            </Action>
        </Trigger>
    </Triggers>
    <Scenes>
    	<Scene id="Intro" lang="en">
            <Text>Here is the introduction</Text>
        </Scene>
        <Scene id="Intro" lang="de">
            <Text>Hier kommt die Einf√ºhrung</Text>
        </Scene>
    	<Scene id="ReachedA" lang="en">
            <Text>You have now reached the first goal, now go to the next one</Text>
        </Scene>
        <Scene id="ReachedA" lang="de">
            <Text>Das erste Ziel ist erreicht, jetzt kommt das zweite</Text>
        </Scene>
    	<Scene id="RevisitedStart" lang="en">
            <Text>No, this is the first goal, you've already been here, go to the end!</Text>
        </Scene>
        <Scene id="RevisitedStart" lang="de">
            <Text>Nein, das ist falsch, hier waren wir schon. Auf zum zweiten!</Text>
        </Scene>
    	<Scene id="Started" lang="en">
            <Text>On our way!</Text>
        </Scene>
        <Scene id="Started" lang="de">
            <Text>Jetzt gehts los!</Text>
        </Scene>
    	<Scene id="HaventVisitedStart" lang="en">
            <Text>No, that's not right, you haven't been to the start point yet!</Text>
        </Scene>
        <Scene id="HaventVisitedStart" lang="de">
            <Text>Direkt zum Endziel geht nicht, ohne das erste zu besuchen!</Text>
        </Scene>
    	<Scene id="Finish" lang="en">
            <Text>Congratulations!</Text>
    		<Finish/>
    	</Scene>
        <Scene id="Finish" lang="de">
            <Text>Gratulation!</Text>
            <Finish/>
        </Scene>
    </Scenes>
</Quest>
